### ISSUE TITLE
iconfont 开发文档

### ISSUE THREAD

**Issue by suzyvivi** [suzyvivi/blog#6]
# Iconfont项目开发文档
> 还在为切恼人的icon而头疼吗？还在为各个icon的不同颜色状态而心累吗？iconfont应运而生。已在我们PCW项目中大面积上线使用了。

### iconfont优点
- **轻量性**：一个图标字体比一系列的图像（特别是在Retina屏中使用双倍图像）要小。一旦图标字体加载了，图标就会马上渲染出来，不需要下载一个图像。可以减少请求，还可以配合HTML5离线存储做性能优化。
- **灵活性**：图标字体可以用过font-size属性设置其任何大小，还可以加各种文字效果，包括颜色、Hover状态、透明度、阴影和翻转等效果。可以在任何背景下显示。使用位图的话，必须得为每个不同大小和不同效果的图像输出一个不同文件。
- **兼容性**：网页字体支持所有现代浏览器，包括IE低版本。

### 项目结构
```
|--src                        // svg图片管理目录
|--gitignore                  //不解释
|--README.md                  //不解释
|--demo.css                   //下方demo页面中的样式，跟iconfont并无关联
|--demo_fontclass.html        //图标示范展示页面（方式1：通过class引用，兼容ie8+）
|--demo_symbol.html           //图标示范展示页面（方式2：通过svg&js引用，兼容ie9+，未来趋势，支持彩色图标）
|--demo_unicode.html          //图标示范展示页面（方式3：通过unicode引用，兼容ie6+，我们项目中采用就是该种方式）
|--iconfont.css               //为方式1生成的样式
|--iconfont.eot               // ie字体文件，已上传cdn
|--iconfont.js                //为方式3生成的js文件
|--iconfont.svg               // ios需要的字体文件，已上传cdn
|--iconfont.ttf               // android需要的字体文件，已上传cdn
|--iconfont.woff              // chrome firefox 字体文件，已上传cdn
```
- 项目中使用的字体图标均是UDC设计师**黄群**的作品
- 项目中的字体文件均由第三方[阿里图标库](http://www.iconfont.cn/)生成
- 我司项目中字体图标展示：[点我](http://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.9&manage_type=myprojects&projectId=334717) （若无账号请先注册，需登录才可以访问）
- 项目中字体图标**设计规范**和**上传方式**请参考[这里](http://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.12&helptype=draw)
- 如上结构所述，web端会有三种方式引用字体文件，我司使用的是==方式3==，三种方式具体阐述[见此](http://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.13&helptype=code)

### 项目中引用方式

```css
@font-face {
    font-family: 'xiu-ico';
    src: url('//static.iqiyi.com/ppsshow/iconfont/iconfont.eot');
    src: url('//static.iqiyi.com/ppsshow/iconfont/iconfont.eot?#iefix') format('embedded-opentype'),
    url('//static.iqiyi.com/ppsshow/iconfont/iconfont.woff') format('woff'),
    url('//static.iqiyi.com/ppsshow/iconfont/iconfont.ttf') format('truetype'),
    url('//static.iqiyi.com/ppsshow/iconfont/iconfont.svg#xiu-ico') format('svg');
}
.xiu-ico {
    font-family: "xiu-ico"!important;
    font-size: 18px;
    font-style: normal;
    -webkit-font-smoothing: antialiased;
    -webkit-text-stroke-width: .2px;
    -moz-osx-font-smoothing: grayscale;
    user-select: none;
}

```
==上述代码已经一站式打包进PCW blank.css中，固可以在pc端任何角落使用字体图标==

### 使用方法（方式3：unicode法）

```html
<i class="xiu-ico xiu-ico-search">&#xe649;</i>
```
###### 三步走
1. 引用基础class `xiu-ico` 。 
2. 自定义描述class `xiu-ico-search` ;(方式3中该自定义类可加可不加，只是便于代码识别)
3. dom结构中插入unicode `&#xe649;` (该unicode可在demo_unicode.html 或者 [我司阿里图标库](http://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.9&manage_type=myprojects&projectId=334717)中查阅)

### 坑点前瞻
- 阿里图标库固然好，但是有小bug，设计出好的svg图标上传前，一定要先命好名称，**千万不要上传后在阿里图标库里修改svg名称**，否则就会出现图标轮廓走形，锯齿等诡异现象。

---
